name: bravo_connet_v2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔥 FIREBASE
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0

  # 📸 IMÁGENES
  image_picker: ^1.0.7

  # 📁 ARCHIVOS
  file_picker: ^11.0.2

  # 🔗 ABRIR LINKS
  url_launcher: ^6.2.5

  # 🎥 VIDEO
  video_player: ^2.8.2

  # 🔥 SPLASH SCREEN
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # 📱 ICONO DE LA APP
  flutter_launcher_icons: ^0.13.1

# 🔥 CONFIGURACIÓN DEL SPLASH
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png

  android_12:
    image: assets/logo.png
    icon_background_color: "#FFFFFF"

# 📱 CONFIGURACIÓN DEL ICONO
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  # 📂 ASSETS
  assets:
    - assets/logo.png
    - assets/icon.png
