// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDucXyF94pe6QeQjSMH1W7rw0zHYp3swas',
    appId: '1:309395665654:web:32683db7b37d95849832d7',
    messagingSenderId: '309395665654',
    projectId: 'bravo-connet',
    authDomain: 'bravo-connet.firebaseapp.com',
    storageBucket: 'bravo-connet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgwwPBsrFZd8q9atwWmK5xAEHElJKcWKc',
    appId: '1:309395665654:android:b9c988bdd2706c5a9832d7',
    messagingSenderId: '309395665654',
    projectId: 'bravo-connet',
    storageBucket: 'bravo-connet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAonxxK5e9PL5Lqpf5nFRt3tDv6wBtp4D0',
    appId: '1:309395665654:ios:1d667d903a2afc7b9832d7',
    messagingSenderId: '309395665654',
    projectId: 'bravo-connet',
    storageBucket: 'bravo-connet.firebasestorage.app',
    iosBundleId: 'com.example.bravoConnetV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAonxxK5e9PL5Lqpf5nFRt3tDv6wBtp4D0',
    appId: '1:309395665654:ios:1d667d903a2afc7b9832d7',
    messagingSenderId: '309395665654',
    projectId: 'bravo-connet',
    storageBucket: 'bravo-connet.firebasestorage.app',
    iosBundleId: 'com.example.bravoConnetV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDucXyF94pe6QeQjSMH1W7rw0zHYp3swas',
    appId: '1:309395665654:web:837d77a3708f428d9832d7',
    messagingSenderId: '309395665654',
    projectId: 'bravo-connet',
    authDomain: 'bravo-connet.firebaseapp.com',
    storageBucket: 'bravo-connet.firebasestorage.app',
  );
}
